export enum tagTypes {
  buyer = 'buyer',
  Order = 'Order',
  seller = 'seller',
  user = 'user',
  profile = 'profile',
  category = 'category',
  auth = 'auth',
  CheckInOut = 'CheckInOut',
  Employee = 'Employee',
  Projects = 'Projects',
  TaskManagement = 'TaskManagement',
  Leaves = 'Leaves',
  LoginHistory = 'LoginHistory',
  Friendship = 'Friendship',
  ChatMessages = 'ChatMessages',
  admin = 'admin',
  Submissions = 'Submissions',
  allTextFieldFilters = 'allTextFieldFilters',
  GeneralUser = 'GeneralUser',
  Notification = 'Notification',
  testimonials = 'testimonials',
  FileUploads = 'FileUploads',
  vendor = 'vendor',
  subscriptions = 'subscriptions',
  PaymentHistory = 'PaymentHistory',
}

export const tagTypesList = [
  tagTypes.subscriptions,
  tagTypes.Order,
  tagTypes.PaymentHistory,
  tagTypes.buyer,
  tagTypes.vendor,
  tagTypes.seller,
  tagTypes.user,
  tagTypes.category,
  tagTypes.profile,
  tagTypes.Projects,
  tagTypes.Employee,
  tagTypes.TaskManagement,
  tagTypes.Leaves,
  tagTypes.LoginHistory,
  tagTypes.auth,
  tagTypes.Friendship,
  tagTypes.ChatMessages,
  tagTypes.admin,
  tagTypes.Submissions,
  tagTypes.allTextFieldFilters,
  tagTypes.GeneralUser,
  tagTypes.Notification,
  tagTypes.testimonials,
  tagTypes.FileUploads,
];
