export enum tagTypes {
  buyer = 'buyer',
  Product = 'Product',
  ProductCategory = 'ProductCategory',
  Order = 'Order',
  seller = 'seller',
  user = 'user',
  profile = 'profile',
  category = 'category',
  auth = 'auth',
  CheckInOut = 'CheckInOut',
  Employee = 'Employee',
  Projects = 'Projects',
  TaskManagement = 'TaskManagement',
  Leaves = 'Leaves',
  LoginHistory = 'LoginHistory',
  Friendship = 'Friendship',
  ChatMessages = 'ChatMessages',
  admin = 'admin',
  Submissions = 'Submissions',
  allTextFieldFilters = 'allTextFieldFilters',
  GeneralUser = 'GeneralUser',
  Notification = 'Notification',
  testimonials = 'testimonials',
  FileUploads = 'FileUploads',
  vendor = 'vendor',
  subscriptions = 'subscriptions',
  PaymentHistory = 'PaymentHistory',
  UserSaveProduct = 'UserSaveProduct',
  RoutingReminder = 'RoutingReminder',
  ServiceLogger = 'ServiceLogger',
  TipsAndGuid = 'TipsAndGuid',
  User = 'User',
}

export const tagTypesList = Object.values(tagTypes);
