export const transactions = [
  {
    transactionID: '#123456',
    createdAt: '02/10/23 03:16 PM',
    name: { firstName: 'John', lastName: 'Doe' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 545',
    accountHolderName: 'John',
    amount: '$100.00',
    fees: '$20.00',
    paymentGateway: 'Debit Card',
    receiverName: 'John Doe',
    action: 'view',
    email: 'john.doe@example.com',
    packageName: 'silver',
    role: 'user',
  },
  {
    transactionID: '#123457',
    createdAt: '02/10/23 03:20 PM',
    name: { firstName: 'James', lastName: 'Smith' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 123',
    accountHolderName: 'James',
    amount: '$260.00',
    fees: '$30.00',
    paymentGateway: 'Credit Card',
    receiverName: 'John Doe',
    action: 'view',
    email: 'james.smith@example.com',
    packageName: 'gold',
    role: 'companyOwner',
  },
  {
    transactionID: '#123458',
    createdAt: '02/11/23 10:30 AM',
    name: { firstName: 'Alice', lastName: 'Johnson' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 987',
    accountHolderName: 'Alice',
    amount: '$500.00',
    fees: '$50.00',
    paymentGateway: 'Debit Card',
    receiverName: 'Emily Clark',
    action: 'view',
    email: 'alice.johnson@example.com',
    packageName: 'silver',
    role: 'user',
  },
  {
    transactionID: '#123459',
    createdAt: '02/11/23 11:45 AM',
    name: { firstName: 'Bob', lastName: 'Williams' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 654',
    accountHolderName: 'Bob',
    amount: '$700.00',
    fees: '$70.00',
    paymentGateway: 'Credit Card',
    receiverName: 'Michael King',
    action: 'view',
    email: 'bob.williams@example.com',
    packageName: 'gold',
    role: 'companyOwner',
  },
  {
    transactionID: '#123460',
    createdAt: '02/12/23 01:10 PM',
    name: { firstName: 'Sarah', lastName: 'Brown' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 321',
    accountHolderName: 'Sarah',
    amount: '$150.00',
    fees: '$15.00',
    paymentGateway: 'Debit Card',
    receiverName: 'John Doe',
    action: 'view',
    email: 'sarah.brown@example.com',
    packageName: 'silver',
    role: 'user',
  },
  {
    transactionID: '#123461',
    createdAt: '02/12/23 02:50 PM',
    name: { firstName: 'David', lastName: 'Miller' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 852',
    accountHolderName: 'David',
    amount: '$80.00',
    fees: '$8.00',
    paymentGateway: 'Credit Card',
    receiverName: 'John Doe',
    action: 'view',
    email: 'david.miller@example.com',
    packageName: 'gold',
    role: 'companyOwner',
  },
  {
    transactionID: '#123462',
    createdAt: '02/13/23 09:15 AM',
    name: { firstName: 'Chris', lastName: 'Wilson' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 741',
    accountHolderName: 'Chris',
    amount: '$350.00',
    fees: '$35.00',
    paymentGateway: 'Debit Card',
    receiverName: 'John Doe',
    action: 'view',
    email: 'chris.wilson@example.com',
    packageName: 'silver',
    role: 'companyOwner',
  },
  {
    transactionID: '#123463',
    createdAt: '02/13/23 10:30 AM',
    name: { firstName: 'Emma', lastName: 'Moore' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 963',
    accountHolderName: 'Emma',
    amount: '$120.00',
    fees: '$12.00',
    paymentGateway: 'Credit Card',
    receiverName: 'John Doe',
    action: 'view',
    email: 'emma.moore@example.com',
    packageName: 'gold',
    role: 'companyOwner',
  },
  {
    transactionID: '#123464',
    createdAt: '02/14/23 03:45 PM',
    name: { firstName: 'Oliver', lastName: 'Taylor' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 159',
    accountHolderName: 'Oliver',
    amount: '$250.00',
    fees: '$25.00',
    paymentGateway: 'Debit Card',
    receiverName: 'Sarah Green',
    action: 'view',
    email: 'oliver.taylor@example.com',
    packageName: 'silver',
    role: 'companyOwner',
  },
  {
    transactionID: '#123465',
    createdAt: '02/14/23 05:00 PM',
    name: { firstName: 'Sophia', lastName: 'Anderson' },
    profileImage:
      'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=450&h=450&dpr=1',
    accountNumber: '**** **** **** 753',
    accountHolderName: 'Sophia',
    amount: '$190.00',
    fees: '$19.00',
    paymentGateway: 'Credit Card',
    receiverName: 'John Doe',
    action: 'view',
    email: 'sophia.anderson@example.com',
    packageName: 'platinum',
    role: 'companyOwner',
  },
];
