export const demoSittersUserData = [
  {
    personalInformation: {
      email: 'james1234@gmail.com',
      firstName: 'James',
      lastName: 'Tracy',
      gender: 'Male',
      age: 24,
      contactNumber: '+1-800-925-6278',
    },
    homeAddress: {
      address: 'New York, USA',
      city: 'Ny',
      county: 'Ny',
      country: 'USA',
      state: 'Albany',
      zipCode: '12345',
    },
    additionalInformation: {
      language: 'English',
      education: 'High school degree',
      occupation: 'RBT',
      experience: '5 years',
      resume: 'Click here',
      aboutYourself:
        'By signing up for our auto-renewing monthly membership, which will be charged to the card on file every 30 days.',
      backgroundCheck:
        'By signing up for our auto-renewing monthly membership, which will be charged to the card on file every 30 days.',
    },
    userUniqueId: 'GA-000123',
    createdAt: '2014-02-25',
  },
  {
    personalInformation: {
      email: 'sarah456@gmail.com',
      firstName: 'Sarah',
      lastName: 'Conner',
      gender: 'Female',
      age: 30,
      contactNumber: '+1-800-123-4567',
    },
    homeAddress: {
      address: 'Los Angeles, USA',
      city: 'LA',
      county: 'Los Angeles',
      country: 'USA',
      state: 'California',
      zipCode: '90001',
    },
    additionalInformation: {
      language: 'English',
      education: "Bachelor's Degree",
      occupation: 'Software Engineer',
      experience: '7 years',
      resume: 'Click here',
      aboutYourself:
        'Tech enthusiast and software engineer with 7 years of experience.',
      backgroundCheck: 'Clear',
    },
    userUniqueId: 'GA-000124',
    createdAt: '2014-02-25',
  },
  {
    personalInformation: {
      email: 'johnDoe789@gmail.com',
      firstName: 'John',
      lastName: 'Doe',
      gender: 'Male',
      age: 35,
      contactNumber: '+1-800-999-8888',
    },
    homeAddress: {
      address: 'Chicago, USA',
      city: 'Chicago',
      county: 'Cook',
      country: 'USA',
      state: 'Illinois',
      zipCode: '60601',
    },
    additionalInformation: {
      language: 'Spanish',
      education: "Master's Degree",
      occupation: 'Business Analyst',
      experience: '10 years',
      resume: 'Click here',
      aboutYourself:
        'Experienced business analyst with a focus on data-driven insights.',
      backgroundCheck: 'Clear',
    },
    userUniqueId: 'GA-000125',
    createdAt: '2014-02-25',
  },
  {
    personalInformation: {
      email: 'emilySmith123@gmail.com',
      firstName: 'Emily',
      lastName: 'Smith',
      gender: 'Female',
      age: 28,
      contactNumber: '+1-800-654-3210',
    },
    homeAddress: {
      address: 'Miami, USA',
      city: 'Miami',
      county: 'Miami-Dade',
      country: 'USA',
      state: 'Florida',
      zipCode: '33101',
    },
    additionalInformation: {
      language: 'English',
      education: 'PhD',
      occupation: 'Data Scientist',
      experience: '6 years',
      resume: 'Click here',
      aboutYourself: 'Passionate about data science and machine learning.',
      backgroundCheck: 'Clear',
    },
    userUniqueId: 'GA-000126',
    createdAt: '2014-02-25',
  },
  {
    personalInformation: {
      email: 'michaelBrown789@gmail.com',
      firstName: 'Michael',
      lastName: 'Brown',
      gender: 'Male',
      age: 45,
      contactNumber: '+1-800-876-5432',
    },
    homeAddress: {
      address: 'Austin, USA',
      city: 'Austin',
      county: 'Travis',
      country: 'USA',
      state: 'Texas',
      zipCode: '73301',
    },
    additionalInformation: {
      language: 'English',
      education: 'MBA',
      occupation: 'Marketing Manager',
      experience: '15 years',
      resume: 'Click here',
      aboutYourself: 'Expert in marketing strategies and brand management.',
      backgroundCheck: 'Clear',
    },
    userUniqueId: 'GA-000127',
    createdAt: '2014-02-25',
  },
];
